update cli
primihub/primihub-docs pull request #183
Opened 2023-07-11 13:31 UTC by fuxingbit

2023-07-11 13:32 UTC, fuxingbit commented
don't merge

2023-08-14 15:11 UTC, xuefeng-xu requested changes

2023-08-14 15:11 UTC, xuefeng-xu commented on docs/advance-usage/create-tasks/1-mpc-task.md
> +下载二进制文件或本地编译启动，在代码根目录下执行以下命令，通过`docker-compose`启动时，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令：
感觉这样写更好，下面的可以统一：
如果是下载二进制文件或本地编译启动，编译完成后在代码根目录下执行以下命令；如果是通过docker-compose启动，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令。

2023-08-14 15:11 UTC, xuefeng-xu commented on i18n/en/docusaurus-plugin-content-docs/current/advance-usage/create-tasks/3-psi-task.md
> +If starting locally, run the following command from the compiled root directory,if starting with docker-compose, enter the primihub-node0 container by running `docker exec -it primihub-node0 bash` ，a
```suggestion
If starting locally, run the following command from the compiled root directory. If starting with docker-compose, enter the `primihub-node0` container by running `docker exec -it primihub-node0 bash`, then run the following command.
```

2023-08-15 02:58 UTC, xuefeng-xu requested changes

2023-08-15 02:58 UTC, xuefeng-xu commented on i18n/en/docusaurus-plugin-content-docs/current/advance-usage/create-tasks/4-pir-task.md
> +If starting locally, run the following command from the compiled root directory,if starting with docker-compose, enter the primihub-node0 container by running`docker exec -it primihub-node0 bash` ，an
```suggestion
If starting locally, run the following command from the compiled root directory. If starting with docker-compose, enter the `primihub-node0` container by running `docker exec -it primihub-node0 bash`, then run the following command.
```

2023-08-15 02:58 UTC, xuefeng-xu commented on i18n/en/docusaurus-plugin-content-docs/current/advance-usage/create-tasks/1-mpc-task.md
> +If starting locally, run the following command from the compiled root directory,if starting with docker-compose, enter the primihub-node0 container by running `docker exec -it primihub-node0 bash`,an
```suggestion
If starting locally, run the following command from the compiled root directory. If starting with docker-compose, enter the `primihub-node0` container by running `docker exec -it primihub-node0 bash`, then run the following command.
```

2023-08-15 02:58 UTC, xuefeng-xu commented on docs/advance-usage/create-tasks/1-mpc-task.md
> +下载二进制文件或本地编译启动，在代码根目录下执行以下命令，通过`docker-compose`启动时，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令：
```suggestion
如果是通过下载二进制文件或本地编译启动，编译完成后在代码根目录下执行以下命令；如果是通过docker-compose启动，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令。
```

2023-08-15 02:58 UTC, xuefeng-xu commented on docs/advance-usage/create-tasks/3-psi-task.md
> +下载二进制文件或本地编译启动，在代码根目录下执行以下命令，通过`docker-compose`启动时，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令：(以下两个任务使用了不同协议)
```suggestion
如果是通过下载二进制文件或本地编译启动，编译完成后在代码根目录下执行以下命令；如果是通过docker-compose启动，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令（以下两个任务使用了不同协议）。
```

2023-08-15 02:58 UTC, xuefeng-xu commented on docs/advance-usage/create-tasks/4-pir-task.md
> +下载二进制文件或本地编译启动，在代码根目录下执行以下命令，通过`docker-compose`启动时，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令：
```suggestion
如果是通过下载二进制文件或本地编译启动，编译完成后在代码根目录下执行以下命令；如果是通过docker-compose启动，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令。
```

2023-08-15 02:58 UTC, xuefeng-xu commented on docs/advance-usage/create-tasks/fedreated-learning/0-hetero-xgb.md
> +* 如果是下载二进制文件或本地编译启动，在编译完成后的代码根目录下执行以下命令，如果是通过docker-compose启动，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令：
```suggestion
* 如果是通过下载二进制文件或本地编译启动，编译完成后在代码根目录下执行以下命令；如果是通过docker-compose启动，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令。
```

2023-08-15 02:58 UTC, xuefeng-xu commented on docs/advance-usage/create-tasks/fedreated-learning/1-hfl-fedavg.md
> +- 如果是下载二进制文件或本地编译启动，在编译完成后的代码根目录下执行以下命令，如果是通过docker-compose启动，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令：
```suggestion
- 如果是通过下载二进制文件或本地编译启动，编译完成后在代码根目录下执行以下命令；如果是通过docker-compose启动，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令。
```

2023-08-15 02:58 UTC, xuefeng-xu commented on docs/advance-usage/create-tasks/fedreated-learning/2-hfl-logistic_regression-paillier.md
> +- 如果是下载二进制文件或本地编译启动，在编译完成后的代码根目录下执行以下命令，如果是通过docker-compose启动，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令：
```suggestion
- 如果是通过下载二进制文件或本地编译启动，编译完成后在代码根目录下执行以下命令；如果是通过docker-compose启动，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令。
```

2023-08-15 02:58 UTC, xuefeng-xu commented on docs/advance-usage/create-tasks/fedreated-learning/3-hfl-dpsgd.md
> +- 如果是下载二进制文件或本地编译启动，在编译完成后的代码根目录下执行以下命令，如果是通过docker-compose启动，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令：
```suggestion
- 如果是通过下载二进制文件或本地编译启动，编译完成后在代码根目录下执行以下命令；如果是通过docker-compose启动，先执行 `docker exec -it primihub-node0 bash` 进入到 `primihub-node0` 容器中，再执行以下命令。
```

2023-08-15 03:03 UTC, xuefeng-xu approved these changes

2023-08-15 03:05 UTC, merged