:memo: Updating documents and cleaning useless files
primihub/primihub-docs pull request #97
Opened 2022-11-14 08:50 UTC by lzw9560

:memo: update

2022-11-14 09:03 UTC, LinuxSuRen requested changes

2022-11-14 09:03 UTC, LinuxSuRen commented on docs/advance-usage/fedreated-learning/0-hetero-xgb.md
> +sidebar_position: 10
Please consider giving a different value from [this one](https://github.com/primihub/primihub-docs/pull/97/files#diff-9fc7490496880ab145e2895107e5fd7b5d07479282116f6dd458e39f9a3c6404R2).

2022-11-14 10:19 UTC, lzw9560 commented on docs/quick-start.md
> +[运行一个纵向联邦学习](https://docs.primihub.com/docs/advance-usage/fedreated-learning/hetero-xgb/)
fixed

2022-11-14 10:20 UTC, lzw9560 commented on docs/advance-usage/fedreated-learning/0-hetero-xgb.md
> +sidebar_position: 10
fixed

2022-11-15 05:26 UTC, LinuxSuRen approved these changes

2022-11-15 05:26 UTC, merged